### ISSUE TITLE
May I ask why I encountered an error when running main.py

### ISSUE THREAD

**Issue by Pt2Mu** [lab-emi/OpenDPD#2]
::: Are Deterministic Algorithms Enabled:  False
--------------------------------------------------------------------
####################################################################################################
# Step: Train PA                                                                                   #
####################################################################################################
::: Available GPUs: 1
::: Using GPU 0:   NVIDIA GeForce RTX 2060
--------------------------------------------------------------------
Backbone Initialized...
::: Number of PA Model Parameters:  486
::: Best Model Save Path:  ./save\DPA_100MHz\train_pa\PA_S_0_M_DGRU_H_8_F_50_P_486.pt
::: Log-History     Path:  ./log\DPA_100MHz\train_pa\history\PA_S_0_M_DGRU_H_8_F_50_P_486.csv
::: Log-Best        Path:  ./log\DPA_100MHz\train_pa\best\PA_S_0_M_DGRU_H_8_F_50_P_486.csv
Starting training...
100%|██████████| 360/360 [00:01<00:00, 237.45it/s]
100%|██████████| 1/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "E:\文献\OpenDPD-main\main.py", line 16, in <module>
    train_pa.main(proj)
  File "E:\文献\OpenDPD-main\steps\train_pa.py", line 50, in main
    proj.train(net=net,
  File "E:\文献\OpenDPD-main\project.py", line 289, in train
    self.log_val = calculate_metrics(self.args, self.log_val, prediction, ground_truth)
  File "E:\文献\OpenDPD-main\modules\train_funcs.py", line 95, in calculate_metrics
    stat['EVM'] = metrics.EVM(prediction, ground_truth, bw_main_ch=args.bw_main_ch, n_sub_ch=args.n_sub_ch, nperseg=args.nperseg)
AttributeError: 'Namespace' object has no attribute 'bw_main_ch'

进程已结束，退出代码为 1

**Comment by UestcPeng1** [comment]
That's because you have chinese in your project path
