### ISSUE TITLE
Results visualization

### ISSUE THREAD

**Issue by shawrby** [lab-emi/OpenDPD#3]
Thank you for your excellent research. 

How can I visualize the results as shown in the paper?

**Comment by gaochangw** [comment]
Hi, thank you for your interest and compliment on our work! The plots in our papers are mostly downloaded from the measurement device directly. But we do have plan this summer vacation to add PSD and constellation plotting functions to OpenDPD. For the moment, probably you can extract some useful function from this tutorial made by us: https://colab.research.google.com/drive/1oVcHuw0F_YtNJe7wGKijxm83K05oOY24?usp=sharing

**Comment by shawrby** [comment]
Oh, thank you very much!
Once again, thank you for your excellent contribution.!
